---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  install_strategy: always
  chef_license: accept
  require_chef_omnibus: 16

verifier:
  name: inspec

platforms:
- name: windows-2016
  driver:
    box: mwrock/Windows2016
    gui: false

suites:
- name: nssm_test
  run_list:
    - nssm_test::install_service
  attributes:

- name: nssm_test_modification
  run_list:
    - nssm_test::modify_service
  attributes:
